apiVersion: v1
kind: Service
metadata:
  name: datadog-cluster-agent
  namespace: default
  labels:
    app: datadog-cluster-agent
spec:
  ports:
    - port: 5005
      targetPort: 5005
      protocol: TCP
      name: cluster-agent
  selector:
    app: datadog-cluster-agent
