apiVersion: apps/v1
kind: Deployment
metadata:
  name: datadog-cluster-agent
  namespace: default
  labels:
    app: datadog-cluster-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: datadog-cluster-agent
  template:
    metadata:
      labels:
        app: datadog-cluster-agent
    spec:
      serviceAccountName: datadog-cluster-agent  # Add service account
      containers:
        - name: cluster-agent
          image: "gcr.io/datadoghq/cluster-agent:latest"
          env:
            - name: DD_API_KEY
              valueFrom:
                secretKeyRef:
                  name: datadog-secret
                  key: api-key
            - name: DD_SITE
              value: {{ .Values.datadog.site | quote }}
            - name: DD_CLUSTER_NAME
              value: {{ .Values.datadog.clusterName | quote }}
            - name: DD_COLLECT_KUBERNETES_EVENTS
              value: "true"
            - name: DD_CLUSTER_AGENT_KUBERNETES_SERVICE_NAME  # Communicate with node agents
              value: "datadog-cluster-agent"
          ports:
            - containerPort: 5005
              name: cluster-agent
          resources:
            limits:
              memory: {{ .Values.datadog.resources.limits.memory }}
              cpu: {{ .Values.datadog.resources.limits.cpu }}
            requests:
              memory: {{ .Values.datadog.resources.requests.memory }}
              cpu: {{ .Values.datadog.resources.requests.cpu }}
